# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0003_guncelyazi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guncelyazi',
            name='yazi',
            field=models.CharField(max_length=200),
        ),
    ]
