# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-16 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mavi', '0004_auto_20160909_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='gorebilecek_kisiler',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
